# -*- coding: utf-8 -*-
"""TA judul2_Sorting.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jgRPB33YAtZ9x6NoMRqjAXp5aRhhnjBw
"""

def tukar(arr, i, j):
    temp = arr[i]
    arr[i] = arr[j]
    arr[j] = temp


def bubble_sort(arr, n):
    for i in range(n - 1):
        for j in range(n - i - 1):
            if arr[j].lower() > arr[j + 1].lower():
                tukar(arr, j, j + 1)


def main():
    try:
        n = int(input("Masukkan jumlah mahasiswa: "))
    except ValueError:
        print("Input tidak valid!")
        return

    arr = []
    print("Masukkan nama mahasiswa:")
    for i in range(n):
        nama = input(f"Nama ke-{i+1}: ")
        arr.append(nama)

    print("\nData sebelum diurutkan:")
    for i in range(n):
        print(f"{i+1}. {arr[i]}")

    bubble_sort(arr, n)

    print("\nData setelah diurutkan (Bubble Sort):")
    for i in range(n):
        print(f"{i+1}. {arr[i]}")


if __name__ == "__main__":
    main()