# -*- coding: utf-8 -*-
"""tugas_akhir_judul1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17sA2t-muU5XwIvgO10gjSFqLI0-1JOQg
"""

def main():
    keranjang = []
    harga = []

    while True:
        print("\nMenu:")
        print("1. Tambah Barang")
        print("2. Tampilkan Keranjang")
        print("3. Hapus Barang")
        print("4. Bayar")
        print("5. Keluar")

        pilihan = input("Pilih menu: ")

        if pilihan == "1":
            nama = input("Masukkan nama barang: ")
            hrg = int(input("Masukkan harga barang: ").replace(".", ""))
            keranjang.append(nama)
            harga.append(hrg)

        elif pilihan == "2":
            if len(keranjang) == 0:
                print("Keranjang kosong")
            else:
                print("\nIsi Keranjang:")
                for i in range(len(keranjang)):
                    print(f"{i+1}. {keranjang[i]} - Rp{harga[i]}")

        elif pilihan == "3":
            if len(keranjang) == 0:
                print("Keranjang kosong")
            else:
                print("\nIsi Keranjang:")
                for i in range(len(keranjang)):
                    print(f"{i+1}. {keranjang[i]} - Rp{harga[i]}")

                try:
                    jumlah = int(input("Berapa barang yang ingin dihapus? "))
                except ValueError:
                    print("Input tidak valid")
                    continue

                for _ in range(jumlah):
                    try:
                        idx = int(input("Pilih nomor barang yang dihapus: ")) - 1
                        if 0 <= idx < len(keranjang):
                            print(f"{keranjang[idx]} dihapus")
                            keranjang.pop(idx)
                            harga.pop(idx)
                        else:
                            print("Index tidak valid")
                    except ValueError:
                        print("Input tidak valid")

        elif pilihan == "4":
            if len(keranjang) == 0:
                print("Keranjang kosong, tidak bisa bayar")
            else:
                total = sum(harga)
                print(f"Total belanja = Rp{total}")

                bayar = int(input("Masukkan uang bayar: ").replace(".", ""))

                if bayar < total:
                    print("Uang tidak cukup")
                else:
                    kembalian = bayar - total

                    print("\n===== KWITANSI =====")
                    for i in range(len(keranjang)):
                        print(f"{i+1}. {keranjang[i]} - Rp{harga[i]}")
                    print("-------------------")
                    print(f"Total = Rp{total}")
                    print(f"Bayar = Rp{bayar}")
                    print(f"Kembalian = Rp{kembalian}")
                    print("===================")

                    keranjang.clear()
                    harga.clear()

        elif pilihan == "5":
            print("Terima kasih")
            break

        else:
            print("Pilihan tidak valid")

if __name__ == "__main__":
  main()